apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: spesialist-db-migrations
  namespace: tbd
  labels:
    team: tbd
    db_policy_user: spesialistbruker
spec:
  image: {{image}}
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  envFrom:
    - secret: google-sql-spesialist-spesialist-spesialist-db-migrati-ae560801
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
