apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spesialist
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://spesialist.intern.dev.nav.no
  strategy:
    type: Recreate
  startup:
    path: isready
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 9
  liveness:
    path: isalive
  readiness:
    path: isready
  preStopHook:
    http:
      path: /stop
  resources:
    limits:
      memory: 640Mi
    requests:
      cpu: 20m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "611669fa-de5c-4dc2-a0e8-6041a019992a" # speil-brukere-prod - har du tilgang i prod har du tilgang i dev også er tanken her
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c" # gammel hjemmemekka tbd-gruppe
          - id: "c0227409-2085-4eb2-b487-c4ba270986a3" # nais-tbd
          - id: "c811e9f4-26a6-43f9-b930-8c83365683a9" # 0000-AZ-speil-kode7-dev
          - id: "dd4e2415-b68d-43a4-87b5-fe2ba5f1dc61" # speil-besluttere-dev
          - id: "317665ad-1402-458e-b8e6-9cb50afc1252" # speil-brukere-dev
  accessPolicy:
    inbound:
      rules:
        - application: speil
          cluster: dev-gcp
        - application: speil-next
          cluster: dev-gcp
    outbound:
      rules:
        - application: spleis-api
          namespace: tbd
          cluster: dev-gcp
        - application: digdir-krr-proxy
          namespace: team-rocket
          cluster: dev-gcp
        - application: logging
          namespace: nais-system
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudprofiler.agent
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        tier: db-custom-1-3840
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: 'write'
        databases:
          - name: spesialist
            envVarPrefix: DATABASE
            users:
              - name: spesialist-db-migrations
              - name: spesialist-opprydding-dev
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spesialist-v1
    - name: TILGANGSGRUPPE_UUID_BESLUTTER
      value: dd4e2415-b68d-43a4-87b5-fe2ba5f1dc61
    - name: TILGANGSGRUPPE_UUID_EGEN_ANSATT
      value: f787f900-6697-440d-a086-d5bb56e26a9c
    - name: TILGANGSGRUPPE_UUID_KODE_7
      value: c811e9f4-26a6-43f9-b930-8c83365683a9
    - name: TILGANGSGRUPPE_UUID_STIKKPROVE
      value: f787f900-6697-440d-a086-d5bb56e26a9c
    - name: TILGANGSGRUPPE_UUID_TBD
      value: f787f900-6697-440d-a086-d5bb56e26a9c
    - name: SPLEIS_CLIENT_ID
      value: api://dev-gcp.tbd.spleis-api/.default
    - name: SPLEIS_API_URL
      value: "http://spleis-api"
    - name: SPLEIS_CLIENT_LOGG_RESPONS
      value: "true"
    - name: BRUK_DUMMY_FOR_KONTAKT_OG_RESERVASJONSREGISTERET
      value: "true"
    - name: TILLAT_GODKJENNING_UTEN_BESLUTTERTILGANG
      value: "true"
    - name: TILLAT_GODKJENNING_AV_EGEN_SAK
      value: "true"
    - name: IGNORER_MELDINGER_FOR_UKJENTE_PERSONER
      value: "true"
    - name: JDK_JAVA_OPTIONS
      value: -agentpath:/opt/cprof/profiler_java_agent.so=-cprof_service=spesialist,-cprof_enable_heap_sampling=true,-logtostderr,-minloglevel=1,-cprof_project_id=tbd-dev-7ff9
    - name: EKSPONER_OPENAPI
      value: "true"
