apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spesialist-migrering
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 3
    max: 3
    cpuThresholdPercentage: 90
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  envFrom:
    - secret: google-sql-spesialist-spesialist-spesialist-migrering-3ec80e91
    - secret: google-sql-sparsom-sparsom-spesialist-migrering-sparso-19bb4184
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spesialist-migrering-v2
    - name: KAFKA_RESET_POLICY
      value: latest
    - name: DATABASE_SPESIALIST_MIGRERING_REGION
      value: "europe-north1"
    - name: DATABASE_SPESIALIST_MIGRERING_INSTANCE
      value: "spesialist"
    - name: DATABASE_SPESIALIST_MIGRERING_SPARSOM_REGION
      value: "europe-north1"
    - name: DATABASE_SPESIALIST_MIGRERING_SPARSOM_INSTANCE
      value: "sparsom"
