apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spesialist
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  startup:
    path: isready
    initialDelay: 90
    periodSeconds: 5
    failureThreshold: 9
  liveness:
    path: isalive
  readiness:
    path: isready
  preStopHook:
    http:
      path: /stop
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 768Mi
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  replicas:
    min: 8
    max: 8
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "611669fa-de5c-4dc2-a0e8-6041a019992a" # saksbehandler (speil-brukere)
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c" # gammel hjemmemekka tbd-gruppe
          - id: "c0227409-2085-4eb2-b487-c4ba270986a3" # nais-tbd
          - id: "9ec6487d-f37a-4aad-a027-cd221c1ac32b" # kode 7
          - id: "e750ceb5-b70b-4d94-b4fa-9d22467b786b" # egne ansatte
          - id: "59f26eef-0a4f-4038-bf46-3a5b2f252155" # beslutter
          - id: "e382880a-e12f-4d56-a92e-2283d7da43af" # stikkprøver
          - id: "39c09f12-4a2f-44da-ab6a-ac43d680294c" # spesialsaker
  accessPolicy:
    inbound:
      rules:
        - application: speil
          namespace: tbd
          cluster: prod-gcp
    outbound:
      rules:
        - application: spleis-api
          namespace: tbd
          cluster: prod-gcp
        - application: digdir-krr-proxy
          namespace: team-rocket
          cluster: prod-gcp
      external:
        - host: tbd-unleash-api.nav.cloud.nais.io
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudprofiler.agent
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        pointInTimeRecovery: true
        diskSize: 1024
        diskType: SSD
        name: spesialist
        tier: db-custom-10-20480
        retainedBackups: 14
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: 'write'
        databases:
          - name: spesialist
            envVarPrefix: DATABASE
            users:
              - name: bigquery_connection_user
              - name: spesialist-sidegig
  envFrom:
    - secret: spesialist-unleash-api-token
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spesialist-v1
    - name: KAFKA_RESET_POLICY
      value: none
    - name: KODE7_SAKSBEHANDLER_GROUP
      value: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
    - name: BESLUTTER_SAKSBEHANDLER_GROUP
      value: 59f26eef-0a4f-4038-bf46-3a5b2f252155
    - name: SKJERMEDE_PERSONER_GROUP
      value: e750ceb5-b70b-4d94-b4fa-9d22467b786b
    - name: SPLEIS_CLIENT_ID
      value: api://prod-gcp.tbd.spleis-api/.default
    - name: SAKSBEHANDLERE_MED_TILGANG_TIL_STIKKPROVER
      value: e382880a-e12f-4d56-a92e-2283d7da43af
    - name: STIKKPROEVER_UTS_FLERE_AG_FGB_DIVISOR #Kan settes til 1 for å slå av automatisering
      value: "200"
    - name: STIKKPROEVER_UTS_FLERE_AG_FORLENGELSE_DIVISOR
      value: "400"
    - name: STIKKPROEVER_UTS_EN_AG_FGB_DIVISOR
      value: "300"
    - name: STIKKPROEVER_UTS_EN_AG_FORLENGELSE_DIVISOR
      value: "500"
    - name: STIKKPROEVER_FULL_REFUSJON_FLERE_AG_FGB_DIVISOR
      value: "300"
    - name: STIKKPROEVER_FULL_REFUSJON_FLERE_AG_FORLENGELSE_DIVISOR
      value: "500"
    - name: STIKKPROEVER_FULL_REFUSJON_EN_AG_DIVISOR
      value: "1000"
    - name: SPLEIS_API_URL
      value: "http://spleis-api"
    - name: KONTAKT_OG_RESERVASJONSREGISTERET_API_URL
      value: "http://digdir-krr-proxy.team-rocket.svc.cluster.local"
    - name: KONTAKT_OG_RESERVASJONSREGISTERET_SCOPE
      value: "api://prod-gcp.team-rocket.digdir-krr-proxy/.default"
    - name: JDK_JAVA_OPTIONS
      value: -agentpath:/opt/cprof/profiler_java_agent.so=-cprof_service=spesialist,-cprof_enable_heap_sampling=true,-logtostderr,-minloglevel=1,-cprof_project_id=tbd-prod-eacd
