apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spesialist
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://spesialist.intern.nav.no
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 4000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 512Mi
  replicas:
    disableAutoScaling: true
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  webproxy: true
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "611669fa-de5c-4dc2-a0e8-6041a019992a"
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c"
          - id: "9ec6487d-f37a-4aad-a027-cd221c1ac32b"
          - id: "e750ceb5-b70b-4d94-b4fa-9d22467b786b"
          - id: "59f26eef-0a4f-4038-bf46-3a5b2f252155"
          - id: "e382880a-e12f-4d56-a92e-2283d7da43af"
          - id: "39c09f12-4a2f-44da-ab6a-ac43d680294c"
  filesFrom:
    - configmap: spesialist-data
      mountPath: /var/run/configmaps
  accessPolicy:
    inbound:
      rules:
        - application: speil
          namespace: tbd
          cluster: prod-gcp
    outbound:
      rules:
        - application: spleis-api
          namespace: tbd
          cluster: prod-gcp
        - application: digdir-krr-proxy
          namespace: team-rocket
          cluster: prod-gcp
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        pointInTimeRecovery: true
        diskSize: 1024
        diskType: SSD
        name: spesialist
        tier: db-custom-22-135168
        retainedBackups: 14
        databases:
          - name: spesialist
            envVarPrefix: DATABASE
            users:
              - name: spesialist-migrering
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spesialist-v1
    - name: KAFKA_RESET_POLICY
      value: none
    - name: KODE7_SAKSBEHANDLER_GROUP
      value: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
    - name: BESLUTTER_SAKSBEHANDLER_GROUP
      value: 59f26eef-0a4f-4038-bf46-3a5b2f252155
    - name: SKJERMEDE_PERSONER_GROUP
      value: e750ceb5-b70b-4d94-b4fa-9d22467b786b
    - name: SPLEIS_CLIENT_ID
      value: api://prod-gcp.tbd.spleis-api/.default
    - name: SAKSBEHANDLERE_MED_TILGANG_TIL_STIKKPROVER
      value: e382880a-e12f-4d56-a92e-2283d7da43af
    - name: SAKSBEHANDLERE_MED_TILGANG_TIL_SPESIALSAKER
      value: 39c09f12-4a2f-44da-ab6a-ac43d680294c
    - name: STIKKPROEVER_UTS_FLERE_AG_FGB_DIVISOR #Kan settes til 1 for å slå av automatisering
      value: "200"
    - name: STIKKPROEVER_UTS_FLERE_AG_FORLENGELSE_DIVISOR
      value: "400"
    - name: STIKKPROEVER_UTS_EN_AG_FGB_DIVISOR
      value: "300"
    - name: STIKKPROEVER_UTS_EN_AG_FORLENGELSE_DIVISOR
      value: "500"
    - name: STIKKPROEVER_FULL_REFUSJON_FLERE_AG_FGB_DIVISOR
      value: "300"
    - name: STIKKPROEVER_FULL_REFUSJON_FLERE_AG_FORLENGELSE_DIVISOR
      value: "500"
    - name: STIKKPROEVER_FULL_REFUSJON_EN_AG_DIVISOR
      value: "1000"
    - name: SPLEIS_API_URL
      value: "http://spleis-api"
    - name: KONTAKT_OG_RESERVASJONSREGISTERET_API_URL
      value: "http://digdir-krr-proxy.team-rocket.svc.cluster.local"
    - name: KONTAKT_OG_RESERVASJONSREGISTERET_SCOPE
      value: "api://prod-gcp.team-rocket.digdir-krr-proxy/.default"
    - name: AUTOMATISER_SPESIALSAK
      value: "true"
