apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spesialist-sidegig
  namespace: tbd
  labels:
    team: tbd
    db_policy_user: spesialistbruker
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 0
    max: 0
    disableAutoScaling: true
    cpuThresholdPercentage: 90
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  envFrom:
    - secret: google-sql-spesialist-spesialist-spesialist-sidegig-507b4532
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_RESET_POLICY
      value: "EARLIEST"
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spesialist-sidegig-v2
    - name: DATABASE_REGION
      value: "europe-north1"
    - name: DATABASE_INSTANCE
      value: "spesialist"
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
