apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spesialist
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  ingresses:
    - https://spesialist.prod-fss.nais.io
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/spesialist/tbd
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvspesialist
      - mountPath: /var/run/secrets/nais.io/azure
        kvPath: /azuread/data/prod/creds/spesialist
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: KAFKA_RAPID_TOPIC
      value: helse-rapid-v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: spesialist-v1
    - name: DATABASE_HOST
      value: a01dbvl011.adeo.no
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: spesialist
    - name: VAULT_MOUNTPATH
      value: postgresql/prod-fss/
    - name: AZURE_CONFIG_URL
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration
    - name: AZURE_REQUIRED_GROUP
      value: 611669fa-de5c-4dc2-a0e8-6041a019992a
    - name: SPLEIS_CLIENT_ID
      value: 60a60e52-7c16-459d-a288-7cc2911c6f81
    - name: SPEIL_CLIENT_ID
      value: c1923167-0725-43fe-91ef-1a5dafc5e246
    - name: SPESIALIST_OID
      value: 5cc46653-7c6c-4c5e-b617-baf648452ad4
