schema: schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://spleis-api.intern.dev.nav.no/graphql/introspection
      headers:
        user-agent: JS GraphQL
      introspect: false
