name: Deploy alerts
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/alerts.yml'
      - 'deploy/alerts/**.yml'

jobs:
  apply-alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/alertconfig.yml,deploy/prod-alerts.yml
