name: Deploy alerts
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/alerts.yml'
      - 'deploy/alerts/**.yml'

jobs:
  apply-alerts:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: deploy/alerts/alertconfig.yml,deploy/alerts/prod-alerts.yml
