name: Gjenbrukbar workflow for docker image

on:
  workflow_call:
    inputs:
      ref:
        description: 'symbolic ref pointing to the commit to build'
        type: string
        default: ${{ github.sha }}
        required: false

    outputs:
      image:
        description: "Navn på imaget som ble bygget"
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    name: Build image
    runs-on: ubuntu-latest-16-cores
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle build
        run: ./gradlew build
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        # Lagt til env-vars for å bøte på hyppig byggfeil av typen "Fatal error	image scan error: scan error: scan failed:..."
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db:1"
        with:
          team: tbd
          tag: ${{ inputs.ref }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
