name: Monitor dependencies with Dependabot
on:
  push:
    branches:
      - master
    paths:
      - "**.gradle.kts"
      - "gradle.properties"
  workflow_dispatch:
jobs:
  dependabot:
    name: Monitor dependencies with Dependabot
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v4 # ratchet:actions/checkout@v4
      - name: Run snapshot action
        uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
