name: Deploy spesifikk commit til dev

on:
  workflow_dispatch:
    inputs:
      commitHash:
        description: 'SHA of the commit to deploy'
        required: true

jobs:
  lag_tag:
    name: Lag en tag
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.lage-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commitHash }}
      - name: Lag tag for senere workflows
        id: lage-tag
        run: |
          export TAG="denne_skal_deployes_til_dev-$(date +%Y-%m-%dT%H.%M.%S)"
          git tag $TAG
          git push origin $TAG
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

  build:
    needs: [ lag_tag ]
    if: ${{ needs.lag_tag.outputs.tag != '' }}
    permissions:
      contents: read
      id-token: write
    uses: navikt/helse-spesialist/.github/workflows/build-image.yml@master
    secrets: inherit
    with:
      ref: ${{ needs.lag_tag.outputs.tag }}

  deployDev:
    name: deploy to dev
    needs: [ lag_tag, build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.lag_tag.outputs.tag }}
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev.yml
          IMAGE: ${{ needs.build.outputs.image }}

  fjern_tag:
    name: Fjern deploy-tag
    permissions:
      contents: write
    needs: [ lag_tag, deployDev ]
    if: ${{ needs.lag_tag.outputs.tag != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git push --delete origin refs/tags/${{ needs.lag_tag.outputs.tag }}
