name: Deploy spesifikk commit til dev

on:
  workflow_dispatch:
    inputs:
      commitHash:
        description: 'SHA of the commit to deploy'
        required: true

jobs:

  build:
    permissions:
      contents: read
      id-token: write
    uses: navikt/helse-spesialist/.github/workflows/build-image.yml@master
    secrets: inherit
    with:
      ref: ${{ github.event.inputs.commitHash }}

  deployDev:
    name: deploy to dev
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commitHash }}
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev.yml
          IMAGE: ${{ needs.build.outputs.image }}
