name: Hovedbygget

on:
    push:
        paths-ignore:
            - 'Dockerfile-opprydding-dev'
            - 'spesialist-opprydding-dev/**'
            - '.github/workflows/spesialist-opprydding-dev.yml'
            - 'deploy/dev-opprydding.yml'
            - 'Dockerfile-migrering'
            - 'spesialist-migrering/**'
            - '.github/workflows/spesialist-migrering.yml'
            - 'deploy/dev-migrering.yml'
            - 'deploy/prod-migrering.yml'
            - '.github/workflows/deploy_specific_commit_to_dev.yml'
            - '.github/workflows/hpa.yml'
            - 'deploy/hpa/**'
            - '.github/workflows/codeql.yml'
            - '.github/workflows/pr.yml'
        branches:
            - master

jobs:
    build:
        permissions:
            contents: read
            id-token: write
        uses: navikt/helse-spesialist/.github/workflows/build-image.yml@master
        secrets: inherit

    deployDev:
        name: Deploy to dev
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: nais/deploy/actions/deploy@v2
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: deploy/dev.yml,deploy/dev-db-policy.yml
                  IMAGE: ${{ needs.build.outputs.image }}

    deployProd:
        name: Deploy to prod
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: nais/deploy/actions/deploy@v2
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: deploy/prod.yml,deploy/prod-db-policy.yml
                  IMAGE: ${{ needs.build.outputs.image }}
