name: Spesialist-opprydding-dev

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile-opprydding-dev'
      - 'spesialist-opprydding-dev/**'
      - 'spesialist-felles/**'
      - 'build.gradle.kts'
      - '.github/workflows/spesialist-opprydding-dev.yml'
      - 'deploy/dev-opprydding.yml'
      - 'deploy/dev-db-policy.yml'
      - '.dockerignore'

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    uses: navikt/helse-spesialist/.github/workflows/build-image.yml@main
    with:
      gradle_command: :spesialist-opprydding-dev:build
      dockerfile: Dockerfile-opprydding-dev
      image_suffix: opprydding-dev
    secrets: inherit

  deployDev:
    name: deploy to dev
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev-opprydding.yml
          IMAGE: ${{ needs.build.outputs.image }}
