name: Spesialist-DB-migrations

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile-db-migrations'
      - 'spesialist-db-migrations/**'
      - '.github/workflows/spesialist-db-migrations.yml'
      - 'deploy/dev-db-migrations.yml'
      - 'deploy/prod-db-migrations.yml'
      - '.dockerignore'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: navikt/helse-spesialist/.github/workflows/build-image.yml@main
    with:
      gradle_command: :spesialist-db-migrations:build
      dockerfile: Dockerfile-db-migrations
      image_suffix: db-migrations
    secrets: inherit
