name: Spesialist-opprydding-dev

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile-opprydding-dev'
      - 'spesialist-opprydding-dev/**'
      - 'spesialist-felles/**'
      - 'build.gradle.kts'
      - '.github/workflows/spesialist-opprydding-dev.yml'
      - 'deploy/dev-opprydding.yml'
      - '.dockerignore'

jobs:
  set_version:
    name: set image name
    runs-on: ubuntu-latest
    steps:
      - name: create docker tag
        run: echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    outputs:
      image: ghcr.io/${{ github.repository }}/spesialist-opprydding-dev:${{ env.TAG }}

  build:
    name: build docker image
    runs-on: ubuntu-latest
    needs: set_version
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.x'
          cache: 'gradle'
      - name: test and build
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :spesialist-opprydding-dev:test :spesialist-opprydding-dev:build

      - name: build docker image
        run: docker build -f Dockerfile-opprydding-dev . --pull -t ${{ needs.set_version.outputs.image }}

      - name: push docker image
        run: |
          docker login --username "$GITHUB_REPOSITORY" -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker push ${{ needs.set_version.outputs.image }}

  deployDev:
    name: deploy to dev
    needs: [set_version, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev-opprydding.yml
          IMAGE: ${{ needs.set_version.outputs.image }}
